package com.openprise.services;

import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.openprise.dao.TestRepository;
@Service
@Transactional
public class ParticipantQuestionService {

	@Autowired
	private SessionFactory sessionFactory;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TestRepository testRepository;
}
