package com.openprise.services;

import javax.inject.Inject;

import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.openprise.dao.ParticipantRepository;
import com.openprise.domain.Participant;
import com.openprise.services.bo.UserTest;

@Service
@Transactional
public class ParticipantService {

	@Autowired
	private SessionFactory sessionFactory;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ParticipantRepository repository;

	@Inject
	private UserTest test;

	public boolean isUserAuthenticated() {
		boolean loggedIn = false;

		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		String mobile = (String) auth.getPrincipal();

		if (mobile != null) {
			Participant p = repository.findByMobile(mobile);
			if (p != null) {
				test.initialize(p);
				loggedIn = true;
			}
		}
		return loggedIn;
	}
}
