package com.openprise.services;

import java.util.ArrayList;
import java.util.List;

import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.openprise.dao.QuestionRepository;
import com.openprise.dao.TestRepository;
import com.openprise.domain.Choice;
import com.openprise.domain.Question;
import com.openprise.domain.TEST_STATUS;
import com.openprise.domain.Test;

@Service
@Transactional
public class TestService {

	@Autowired
	private SessionFactory sessionFactory;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TestRepository testRepository;

	@Autowired
	private QuestionRepository questionRepository;

	public Question addQuestion(long testId, Question q) {

		Test test = testRepository.findOne(testId);

		if (test == null) {

		}
		if (TEST_STATUS.PLANNED.equals(test.getStatus())) {
			if (test.getQuestions() == null) {
				test.setQuestions(new ArrayList<Question>());
			}
			test.getQuestions().add(q);
			testRepository.save(test);
		} else {

		}

		return q;
	}

	public void removeQuestion(long testId, long questionId) {
		Test test = testRepository.findOne(testId);

		if (test == null) {

		}
		if (TEST_STATUS.PLANNED.equals(test.getStatus())) {
			if (test.getQuestions() != null) {
				Question q = questionRepository.findOne(questionId);
				if (q != null)
					test.getQuestions().remove(q);
			}
			testRepository.save(test);
		} else {

		}
	}

	public Question addOptions(long questionId, Choice[] choices) {
		Question q = questionRepository.findOne(questionId);
		if (q != null) {
			if (q.getOptions() == null) {
				q.setOptions(new ArrayList<Choice>());
			}
			for(Choice c: choices) {
				q.getOptions().add(c);
			}
			questionRepository.save(q);
		}
		return q;
	}

	public Question addOption(long questionId, Choice c) {
		Question q = questionRepository.findOne(questionId);
		if (q != null) {
			if (q.getOptions() == null) {
				q.setOptions(new ArrayList<Choice>());
			}
			q.getOptions().add(c);
			questionRepository.save(q);
		}
		return q;
	}
}
