package com.openprise.services;
import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.openprise.dao.UserRepository;
import com.openprise.domain.User;

@Service
@Transactional
public class UserService {

	@Autowired
	private SessionFactory sessionFactory;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	public void saveSomething(User user) {
		Session session = sessionFactory.getCurrentSession();
		session.save(user);
		Criteria c = session.createCriteria(User.class);
		c.add(Restrictions.eq("name", user.getName()));
		List<User> results = c.list();
		System.out.println("Size: " + results.size());

		try {
			System.out.println(user.getId());
			User u = session.load(User.class, user.getId());
			System.out.println(u);
		} catch (Exception e){
			e.printStackTrace();
		}
	}
}
