package com.openprise.web.controller;

import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.openprise.dao.ParticipantTestRepository;
import com.openprise.dao.TestRepository;
import com.openprise.domain.ParticipantQuestion;
import com.openprise.domain.Test;
import com.openprise.domain.TestParticipant;
import com.openprise.services.ParticipantTestService;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/test") // This means URL's start with /demo (after Application path)
//@Path("/test")
public class TestController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ParticipantTestRepository repository;

	@Autowired
	private ParticipantTestService service;
	
	@GET
	@Path("/register/{id}")
	public @ResponseBody  Iterable<TestParticipant>  register(@PathParam("id") int testId) {
		service.registerForCurrentParticipant(testId);
		Iterable<TestParticipant> tests = repository.findAll();
		tests.forEach(it -> {
			it.setQuestions(null);
		});
		return tests;
	}
	
	@GET
	@Path("/{participantTestId}/begin")
	public @ResponseBody ParticipantQuestion begin(@PathParam("id") int participantTestId) {
		ParticipantQuestion question = service.beginTest(participantTestId);
		question.getQuestion().getOptions().forEach(listItem -> {
			listItem.setValid(false);
		});
		return question;
	}
	
	@GET
	@Path("/{participantTestId}/resume")
	public ParticipantQuestion resumeTest(int participantTestId) {
		ParticipantQuestion question = service.resumeTest(participantTestId);
		return question;
	}
	
	@GET
	@Path("/{qId}/skipAnAnswer/{oid}")
	public ParticipantQuestion skipAnAnswer(int questionIndex) {
		ParticipantQuestion question = service.skipAnAnswer(questionIndex);
		return question;
	}

	
	@GET
	@Path("/{qId}/submitAnAnswer/{oid}")
	public ParticipantQuestion submitAnAnswer(int questionIndex, int optionIndex) {
		ParticipantQuestion question = service.submitAnAnswer(questionIndex, optionIndex);
		return question;
	}

	@GET
	@Path("/getNextQuestion")
	public ParticipantQuestion getNextQuestion() {
		ParticipantQuestion question = service.getNextQuestion();
		return question;
	}
	
	@GET
	@Path("/getPrevQuestion")
	public ParticipantQuestion getPrevQuestion() {
		ParticipantQuestion question = service.getPrevQuestion();
		return question;
	}
	
	@GET
	@Path("/getNextPendingQuestion/{index}")
	public ParticipantQuestion getNextPendingQuestion(@PathParam("index") int index) {
		ParticipantQuestion question = service.getNextPendingQuestion(index);
		return question;
	}

	@GET
	@Path("/getPrevPendingQuestion/{index}")
	public ParticipantQuestion getPrevPendingQuestion(@PathParam("index") int index) {
		ParticipantQuestion question = service.getPrevPendingQuestion(index);
		return question;
	}
	
	@GET
	@Path("/getQuestionAt/{index}")
	public ParticipantQuestion getQuestionAt(@PathParam("index") int index) {
		ParticipantQuestion question = service.getQuestionAt(index);
		return question;
	}
	
	@GET
	@Path("/{participantTestId}/end")
	public @ResponseBody String end() {
		service.endTest();
		return "Completed";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<TestParticipant> getAllTests() {
		Iterable<TestParticipant> tests = repository.findAll();
		tests.forEach(it -> {
			it.setQuestions(null);
		});
		return tests;
	}
	
	@GET
	@Path("/test/{id}")
	public @ResponseBody TestParticipant getTest(@PathParam("id") int id) {
		TestParticipant test = repository.findOne(id);
		test.setQuestions(null);
		return test;
	}
	
}
